out_dir: results
metric_best: auc
wandb:
  entity: flos-models
  use: True
  project: LastFM
dataset:
  format: PyG-LastFM
  name: PyG-LastFM
  task: link_pred
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: transductive_edge
  layers_pre_mp: 1
  layers_mp: 3
  layers_post_mp: 1
  dim_inner: 64
  layer_type: gineconv
  act: relu
  residual: True
  dropout: 0.0
optim:
  optimizer: adam
  weight_decay: 0.0
  base_lr: 0.0001
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
