out_dir: results
metric_best: auc
wandb:
  entity: lucastr
  use: True
  project: DISCO-OLGA-eval
dataset:
  format: PyG-DISCOOLGA_triplet
  name: PyG-DISCOOLGA_triplet
  task: link_pred
  task_type: classification
  transductive: True
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: True
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
  embedding: None
  split_mode: custom
  triplets_per_edge: two
  features: 'acousticbrainz_clap'
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: triplet
  edge_decoding: euclidean
  graph_pooling: add
  thresh: 0.62
gnn:
  head: transductive_edge
  layers_pre_mp: 0
  layers_mp: 1
  layers_post_mp: 2
  linear_output_layer: 100 # set to -1 to disable
  dim_inner: 256
  layer_type: sageconv
  act: relu
  residual: False
  dropout: 0.0
optim:
  optimizer: adamW
  weight_decay: 0.05
  base_lr: 0.001
  max_epoch: 200
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 20
  min_lr: 1e-5
  triplet_loss_margin: 0.2
  normalize_embds: True
ndcg_metric:
  use: True
  k: 200
  rate: 10
